=== oscar-system/Oscar.jl/data/schema.json
{
  "$defs": {
    "data": {
      "oneOf": [
        {
          "type": "boolean"
        },
        {
          "type": "string"
        },
        {
          "patternProperties": {
            "^[a-zA-Z0-9_]*": {
              "$ref": "#/$defs/data"
            }
          },
          "type": "object",
          "not": { "required": [ "_ns" ] }
        },
        {
          "items": {
            "$ref": "#/$defs/data"
          },
          "type": "array"
        },
        {
          "$ref": "https://polymake.org/schemas/data.json"
        },
        {
          "type": "null"
        },{
          "not": { "$ref": "#" }
        }
      ]
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "properties": {
            "name": {
              "type": "string"
            },
            "params": {
              "$ref": "#/$defs/params"
            }
          },
          "required": [
            "name"
          ],
          "type": "object"
        }
      ]
    },
    "params": {
      "anyOf": [
        {
          "$ref": "#/$defs/type"
        },
        {
          "$ref": "#"
        },
        {
          "items": {
            "$ref": "#/$defs/params"
          },
          "type": "array"
        },
        {
          "additionalProperties": {
            "$ref": "#/$defs/params"
          },
          "type": "object"
        },
        {
          "$ref": "#/$defs/data"
        }
      ]
    }
  },
  "$id": "https://oscar-system.org/schemas/mrdi.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "_ns": {
      "type": "object"
    },
    "_refs": {
      "patternProperties": {
        "^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$": {
          "$ref": "#"
        }
      },
      "type": "object"
    },
    "_type": {
      "$ref": "#/$defs/type"
    },
    "data": {
      "$ref": "#/$defs/data"
    }
  },
  "required": [
    "_type"
  ],
  "type": "object"
}

=== oscar-system/Oscar.jl/test/Serialization/upgrades/poly1.0.5.json
{
  "_ns": {
    "Oscar": [
      "https://github.com/oscar-system/Oscar.jl",
      "1.0.5"
    ]
  },
  "_type": {
    "name": "MPolyRingElem",
    "params": "f0885e3e-71ff-4813-88fd-7ee05eeb3657"
  },
  "data": [
    [
      [
        "3",
        "4"
      ],
      [
        [
          "0",
          "2"
        ]
      ]
    ],
    [
      [
        "1",
        "0"
      ],
      [
        [
          "1",
          "5"
        ]
      ]
    ],
    [
      [
        "0",
        "2"
      ],
      [
        [
          "0",
          "3"
        ],
        [
          "1",
          "1"
        ]
      ]
    ],
    [
      [
        "0",
        "0"
      ],
      [
        [
          "0",
          "1"
        ]
      ]
    ]
  ],
  "_refs": {
    "f0885e3e-71ff-4813-88fd-7ee05eeb3657": {
      "_type": "MPolyRing",
      "data": {
        "base_ring": "e06a6ac9-954b-4fb7-89c6-f2a25489440e",
        "symbols": [
          "y",
          "z"
        ]
      }
    },
    "e06a6ac9-954b-4fb7-89c6-f2a25489440e": {
      "_type": "FqField",
      "data": {
        "_type": {
          "name": "PolyRingElem",
          "params": "3a66dcbd-bd73-4bb7-8b99-42d9f5177893"
        },
        "data": [
          [
            "0",
            "1"
          ],
          [
            "2",
            "1"
          ]
        ]
      }
    },
    "3a66dcbd-bd73-4bb7-8b99-42d9f5177893": {
      "_type": "PolyRing",
      "data": {
        "base_ring": "221dfa92-69df-4b5a-8f30-166aafddfaa9",
        "symbols": [
          "x"
        ]
      }
    },
    "221dfa92-69df-4b5a-8f30-166aafddfaa9": {
      "_type": "FqField",
      "data": "7"
    }
  }
}
